version: '3.8'

services:
    zookeeper:
            image: confluentinc/cp-zookeeper:latest
            hostname: zookeeper
            container_name: zookeeper
            environment:
              ZOOKEEPER_CLIENT_PORT: 2181
              ZOOKEEPER_TICK_TIME: 2000
            ports:
              - 22181:2181
              
        
    kafka1:
        image: confluentinc/cp-kafka:latest
        hostname: kafka1
        container_name: kafka1
        depends_on:
          - zookeeper
        ports:
          - "9092:9092"
        environment:
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
          KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
          KAFKA_BROKER_ID: 1
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    mysql:
        image: mysql:5.7
        container_name: mysql_db
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: admin
          MYSQL_PASSWORD: admin
        ports:
          - "3306:3306"
        volumes:
          - mysql_data:/var/lib/mysql
    redis:
        image: redis:latest
        container_name: my-redis-container
        ports:
          - "6379:6379"
        volumes:
          - ./redis-data:/data
        networks:
          - redis-net

    redis-insight:
        image: redislabs/redisinsight:latest
        container_name: my-redis-insight
        ports:
          - "8001:8001"
        depends_on:
          - redis
        networks:
          - redis-net

    user-service-app:
        image: user-service:latest
        ports:
          - "8081:8081"
        environment:
          - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/social_media_db
          - SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS=kafka1:9092
          - SPRING_REDIS_HOST=redis
        depends_on:
          - zookeeper
          - kafka1
          - mysql
          - redis
          - redis-insight
volumes:
  mysql_data:
    driver: local
networks:
  redis-net:
    driver: bridge