version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: my-redis-container
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    networks:
      - redis-net

  redis-insight:
    image: redislabs/redisinsight:latest
    container_name: my-redis-insight
    ports:
      - "8001:8001"
    depends_on:
      - redis
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge
