version: '3.8'

services:
  user-service-app:
        image: user-service:latest
        mem_limit: 700m
        ports:
          - "8081:8081"
        environment:
          SPRING_REDIS_HOST: redis
          SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/social_media_db
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: root
          SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka1:9092
          SPRING_KAFKA_TOPIC: "user-event"
          SPRING_KAFKA_PRODUCER_BOOTSTRAP_SERVERS: kafka1:9092
          SPRING_KAFKA_ADMIN_PROPERTIES_BOOTSTRAP_SERVERS: kafka1:9092

volumes:
  mysql_data:
    driver: local