version: '3.8'

services:
  discovery-server:
        image: discovery-server:latest
        ports:
          - "8761:8761"
        networks:
          - standalone_backend-network
  user-service-app:
        image: user-service:latest
        ports:
          - "8081:8081"
        environment:
          SPRING_PROFILES_ACTIVE: prod
          EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-server:8761/eureka
        depends_on:
          - discovery-server
        networks:
          - standalone_backend-network
networks:
  standalone_backend-network:
    external: true